# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "avnav-sail_instrument-plugin"
arch: "all"
platform: "linux"
version: "202404"
license: "MIT"
keep_version: true
section: "default"
priority: "extra"
depends:
  - avnav (>=20220426)
  - python3-scipy
  - python3-numpy
maintainer: "Klaus D. Schmidt <kdschmidt@bluewin.ch>"
description: |
  AvNav plugin supplying Sail_Instrument widgets and overlay
  showing true and apparent wind, tide, laylines
  and optionally optimal VMC course
homepage: "https://github.com/kdschmidt1/Sail_Instrument"
contents:
  - src: ./Sail_Instrument/*
    dst: /usr/lib/avnav/plugins/Sail_Instrument/
