# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "Layline-plugin"
arch: "all"
platform: "linux"
version: "202204"
keep_version: true
section: "default"
priority: "extra"
depends:
- avnav
maintainer: "Klaus D. Schmidt <kdschmidt@bluewin.ch>"
description: |
  AvNav plugin to show a sailsteer display and Laylines on the map
homepage: ""
license: "MIT"
contents:
- src: ./SegelDisplay/*
  dst: /usr/lib/avnav/server/plugins/SegelDisplay/
- src: ./Overlay/*
  dst: /home/pi/avnav/data/overlays/  
